const genresSeed = async (prisma) => {
  await prisma.genre.createMany({
    data: [
      { name: "Rock" },
      { name: "Classic Rock" },
      { name: "Alternative Rock" },
      { name: "Punk Rock" },
      { name: "Indie Rock" },
      { name: "Pop" },
      { name: "Pop Rock" },
      { name: "Dance Pop" },
      { name: "Electropop" },
      { name: "R&B" },
      { name: "Hip Hop" },
      { name: "Rap" },
      { name: "Trap" },
      { name: "Jazz" },
      { name: "Blues" },
      { name: "Soul" },
      { name: "Funk" },
      { name: "Country" },
      { name: "Bluegrass" },
      { name: "Reggae" },
      { name: "Ska" },
      { name: "Electronic" },
      { name: "House" },
      { name: "Techno" },
      { name: "Trance" },
      { name: "Dubstep" },
      { name: "Drum and Bass" },
      { name: "Ambient" },
      { name: "Industrial" },
      { name: "Classical" },
      { name: "Opera" },
      { name: "Metal" },
      { name: "Heavy Metal" },
      { name: "Death Metal" },
      { name: "Black Metal" },
      { name: "Thrash Metal" },
      { name: "Grunge" },
      { name: "Post Rock" },
      { name: "Acoustic" },
      { name: "Folk" },
      { name: "World Music" },
      { name: "Latin" },
      { name: "Salsa" },
      { name: "Bossa Nova" },
      { name: "Reggaeton" },
      { name: "Afrobeat" },
      { name: "K-pop" },
      { name: "J-pop" },
      { name: "Indie Pop" },
      { name: "Baroque" },
      { name: "Gothic" },
      { name: "Emo" },
      { name: "Post Punk" },
      { name: "New Wave" },
      { name: "Synthwave" },
      { name: "Chillwave" },
      { name: "Lo-fi" },
      { name: "Synthpop" },
      { name: "Dancehall" },
      { name: "Disco" },
      { name: "Garage Rock" },
      { name: "Psychedelic Rock" },
      { name: "Progressive Rock" },
      { name: "Art Rock" },
      { name: "Jazz Fusion" },
      { name: "Folk Rock" },
      { name: "Hard Rock" },
      { name: "Post Hardcore" },
      { name: "Pop Punk" },
      { name: "Math Rock" },
      { name: "Lo-fi Hip Hop" },
      { name: "Neo Soul" },
      { name: "Dance Punk" },
      { name: "Electro Swing" },
      { name: "Chiptune" },
      { name: "Vaporwave" },
      { name: "Future Funk" },
      { name: "Tropical House" },
      { name: "Hardstyle" },
      { name: "Eurodance" },
      { name: "Trap EDM" },
      { name: "Post Metal" },
      { name: "Deathcore" },
      { name: "Metalcore" },
      { name: "Post Hardcore" },
      { name: "Screamo" },
      { name: "Djent" },
      { name: "Celtic" },
      { name: "New Age" },
      { name: "Experimental" },
      { name: "Drone" },
      { name: "Post-punk Revival" },
      { name: "Samba" },
      { name: "Bossa Nova" },
      { name: "Forró" },
      { name: "MPB" },
      { name: "Tropicalia" },
      { name: "Choro" },
      { name: "Axé" },
      { name: "Frevo" },
      { name: "Maracatu" },
      { name: "Sertanejo" },
      { name: "Pagode" },
      { name: "Funk Carioca" },
      { name: "Samba Rock" },
      { name: "Maranhão" },
      { name: "Baile de Favela" },
      { name: "Xaxado" },
      { name: "Samba de Roda" },
      { name: "Rádio Nacional" },
      { name: "Carimbó" },
      { name: "Sertanejo Universitário" },
      { name: "Rumba" },
      { name: "Vozes do Sertão" },
    ],
  });
};

export default genresSeed;
